### ISSUE TITLE
FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by highjohnconquer** [AbyszOne/Abysz-LAB-Ext#7]
For some reason I can't your extension and I'm really excited to. I keep running into an error.

 commit: 22bcc7be  •  checkpoint: f037812a2c
 
 (I'm running the latest version of the app)

**Console Data**

To create a public link, set `share=True` in `launch()`.
Startup time: 22.3s (load scripts: 5.1s, reload script modules: 0.2s, list SD models: 2.4s, create ui: 14.5s, gradio launch: 0.2s).
Calculating sha256 for E:\Documents\AI\stable-diffusion-webui\models\Stable-diffusion\icomix_V03Pruned.safetensors: f037812a2c49f851ae88134e88c3dae9c40fa840c6f2f04defff627eeac114e0
Loading weights [f037812a2c] from E:\Documents\AI\stable-diffusion-webui\models\Stable-diffusion\icomix_V03Pruned.safetensors
Applying cross attention optimization (Doggettx).
Weights loaded in 29.3s (calculate hash: 27.3s, load weights from disk: 0.2s, apply weights to model: 0.8s, move model to device: 1.0s).
'magick' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "E:\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Documents\AI\stable-diffusion-webui\extensions\Abysz-LAB-Ext\scripts\Abysz_Lab.py", line 317, in main
    os.rename(os.path.join(maskS, 'result.png'), os.path.join(maskS, f"{name}.png"))
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'E:\\Documents\\AI\\stable-diffusion-webui\\extensions\\Abysz-LAB-Ext\\scripts\\Run\\MaskS\\result.png' -> 'E:\\Documents\\AI\\stable-diffusion-webui\\extensions\\Abysz-LAB-Ext\\scripts\\Run\\MaskS\\0001.png'
'magick' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "E:\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Documents\AI\stable-diffusion-webui\extensions\Abysz-LAB-Ext\scripts\Abysz_Lab.py", line 317, in main
    os.rename(os.path.join(maskS, 'result.png'), os.path.join(maskS, f"{name}.png"))
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'E:\\Documents\\AI\\stable-diffusion-webui\\extensions\\Abysz-LAB-Ext\\scripts\\Run\\MaskS\\result.png' -> 'E:\\Documents\\AI\\stable-diffusion-webui\\extensions\\Abysz-LAB-Ext\\scripts\\Run\\MaskS\\0001.png'

**Settings**
![image](https://user-images.githubusercontent.com/46117736/232177697-1eded79e-98b2-41f1-81c9-03818c6f95b2.png)
![image](https://user-images.githubusercontent.com/46117736/232177721-5f2cd0ac-9332-47af-aa34-133e6083c8a9.png)

**Comment by AbyszOne** [comment]
"'magick' is not recognized as an internal or external command"

You haven't installed Imagemagick library: https://imagemagick.org/script/download.php

**Comment by highjohnconquer** [comment]
Thank you

**Comment by AbyszOne** [comment]
No problem. Tell me any issue.
